### ISSUE TITLE
使用sdk遇到MissingMethodException

### ISSUE THREAD

**Issue by z2665** [TencentCloud/tencentcloud-sdk-dotnet#34]
使用sdk查询cvm实例遇到sdk内部错误提示Method not found
dotnet 环境如下
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.300/
```
paket管理依赖，其中paket.lock如下
```
STORAGE: NONE
RESTRICTION: || (== netcoreapp3.1) (== netstandard2.0) (== netstandard2.1)
NUGET
  remote: https://api.nuget.org/v3/index.json
    FSharp.Core (4.7.2)
    Microsoft.AspNet.WebApi.Client (5.2.7)
      Newtonsoft.Json (>= 10.0.1)
      Newtonsoft.Json.Bson (>= 1.0.1)
    Newtonsoft.Json (12.0.3)
    Newtonsoft.Json.Bson (1.0.2)
      Newtonsoft.Json (>= 12.0.1)
    Pathoschild.Http.FluentClient (4.0)
      Microsoft.AspNet.WebApi.Client (>= 5.2.7)
    System.Buffers (4.5.1) - restriction: || (&& (== netcoreapp3.1) (>= monoandroid)) (&& (== netcoreapp3.1) (>= monotouch)) (&& (== netcoreapp3.1) (>= net461)) (&& (== netcoreapp3.1) (< netcoreapp2.0) (< netstandard2.1)) (&& (== netcoreapp3.1) (< netstandard1.1)) (&& (== netcoreapp3.1) (< netstandard2.0)) (&& (== netcoreapp3.1) (>= uap10.1)) (&& (== netcoreapp3.1) (>= xamarinios)) (&& (== netcoreapp3.1) (>= xamarinmac)) (&& (== netcoreapp3.1) (>= xamarintvos)) (&& (== netcoreapp3.1) (>= xamarinwatchos)) (== netstandard2.0) (&& (== netstandard2.1) (>= net461)) (&& (== netstandard2.1) (>= uap10.1))
    System.Memory (4.5.4) - restriction: || (&& (== netcoreapp3.1) (>= net461)) (&& (== netcoreapp3.1) (< netcoreapp2.1) (< netstandard2.1)) (&& (== netcoreapp3.1) (>= uap10.1)) (== netstandard2.0) (&& (== netstandard2.1) (>= net461)) (&& (== netstandard2.1) (>= uap10.1))
      System.Buffers (>= 4.5.1) - restriction: || (&& (== netcoreapp3.1) (>= monoandroid)) (&& (== netcoreapp3.1) (>= monotouch)) (&& (== netcoreapp3.1) (>= net461)) (&& (== netcoreapp3.1) (< netcoreapp2.0)) (&& (== netcoreapp3.1) (< netstandard1.1)) (&& (== netcoreapp3.1) (< netstandard2.0)) (&& (== netcoreapp3.1) (>= xamarinios)) (&& (== netcoreapp3.1) (>= xamarinmac)) (&& (== netcoreapp3.1) (>= xamarintvos)) (&& (== netcoreapp3.1) (>= xamarinwatchos)) (== netstandard2.0) (== netstandard2.1)
      System.Numerics.Vectors (>= 4.4) - restriction: || (&& (== netcoreapp3.1) (< netcoreapp2.0)) (== netstandard2.0) (== netstandard2.1)
      System.Runtime.CompilerServices.Unsafe (>= 4.5.3) - restriction: || (&& (== netcoreapp3.1) (>= monoandroid)) (&& (== netcoreapp3.1) (>= monotouch)) (&& (== netcoreapp3.1) (>= net461)) (&& (== netcoreapp3.1) (< netcoreapp2.0)) (&& (== netcoreapp3.1) (< netcoreapp2.1)) (&& (== netcoreapp3.1) (< netstandard1.1)) (&& (== netcoreapp3.1) (< netstandard2.0)) (&& (== netcoreapp3.1) (>= uap10.1)) (&& (== netcoreapp3.1) (>= xamarinios)) (&& (== netcoreapp3.1) (>= xamarinmac)) (&& (== netcoreapp3.1) (>= xamarintvos)) (&& (== netcoreapp3.1) (>= xamarinwatchos)) (== netstandard2.0) (== netstandard2.1)
    System.Numerics.Vectors (4.5) - restriction: || (&& (== netcoreapp3.1) (>= net461)) (&& (== netcoreapp3.1) (< netcoreapp2.0) (< netstandard2.1)) (&& (== netcoreapp3.1) (>= uap10.1)) (== netstandard2.0) (&& (== netstandard2.1) (>= net461)) (&& (== netstandard2.1) (>= uap10.1))
    System.Runtime.CompilerServices.Unsafe (4.7.1) - restriction: || (&& (== netcoreapp3.1) (>= monoandroid)) (&& (== netcoreapp3.1) (>= monotouch)) (&& (== netcoreapp3.1) (>= net461)) (&& (== netcoreapp3.1) (< netcoreapp2.0) (< netstandard2.1)) (&& (== netcoreapp3.1) (< netcoreapp2.1) (< netstandard2.1)) (&& (== netcoreapp3.1) (< netstandard1.1)) (&& (== netcoreapp3.1) (< netstandard2.0)) (&& (== netcoreapp3.1) (>= uap10.1)) (&& (== netcoreapp3.1) (>= xamarinios)) (&& (== netcoreapp3.1) (>= xamarinmac)) (&& (== netcoreapp3.1) (>= xamarintvos)) (&& (== netcoreapp3.1) (>= xamarinwatchos)) (== netstandard2.0) (&& (== netstandard2.1) (>= net461)) (&& (== netstandard2.1) (>= uap10.1))
    System.Text.Encodings.Web (4.7.1)
      System.Memory (>= 4.5.4) - restriction: || (&& (== netcoreapp3.1) (>= net461)) (&& (== netcoreapp3.1) (< netcoreapp2.1) (< netstandard2.1)) (&& (== netcoreapp3.1) (>= uap10.1)) (== netstandard2.0) (&& (== netstandard2.1) (>= net461)) (&& (== netstandard2.1) (>= uap10.1))
    TencentCloudSDK (3.0.69)
      Newtonsoft.Json (>= 11.0.1)
      Pathoschild.Http.FluentClient (>= 3.2)
      System.Text.Encodings.Web (>= 4.4)
```
业务代码如下
```f#
 async{
            let region = getRegion(city)
            let cred = Credential(SecretId="*",SecretKey="*")
            let cvmclient =  CvmClient(cred, region)
            let respFilter =  Filter(Name="private-ip-address",Values=Array.ofList ips); // 创建Filter对象, 以内网ip的维度来查询cvm实例
            let req = DescribeInstancesRequest(Filters=[|respFilter|]);
            let! resp = cvmclient.DescribeInstances(req) |> Async.AwaitTask
            Console.WriteLine(AbstractModel.ToJsonString(resp))
        }
```
报错如下
```
System.AggregateException: One or more errors occurred. (Method not found: 'Void Pathoschild.Http.Client.FluentClient..ctor(System.String, System.Net.Http.HttpClient)'.)
 ---> System.MissingMethodException: Method not found: 'Void Pathoschild.Http.Client.FluentClient..ctor(System.String, System.Net.Http.HttpClient)'.
   at TencentCloud.Common.Http.HttpConnection..ctor(String baseUrl, Int32 timeout, String proxy)
   at TencentCloud.Common.AbstractClient.BuildConnection()
   at TencentCloud.Common.AbstractClient.RequestV1(AbstractModel request, String actionName)
   at TencentCloud.Common.AbstractClient.InternalRequest(AbstractModel request, String actionName)
   at TencentCloud.Cvm.V20170312.CvmClient.DescribeInstances(DescribeInstancesRequest req)
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by zqfan** [comment]
看起来应该是SDK依赖的包版本太高了导致的，Pathoschild.Http.FluentClient要求是3.2.0，但是实际环境上装的是4.0，导致SDK使用到的方法找不到了
